export const FETCHING_CLASSES = "FETCHING_CLASSES";
export const FETCHING_CLASSES_SUCCESS = "FETCHING_CLASSES_SUCCESS";
export const FETCHING_CLASSES_FAILURE = "FETCHING_CLASSES_FAILURE";
export const TOGGLE_FILTER_BAR = "TOGGLE_FILTER_BAR";
